inherit_from: .rubocop_todo.yml

# 検査対象から除外する
AllCops:
  Exclude:
    - "db/schema.rb"
    - "spec/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
  DisplayCopNames: true # 警告にCop名を表示する

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

########## Style ##########

# Windows以外で使用することになった場合、改行コードをLFに強要する
Style/EndOfLine:
  Enabled: false
# EnforcedStyle: lf

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 文字列リテラルを凍結するマジックコメントを強要しない
Style/FrozenStringLiteralComment:
  Enabled: false

# 3行程度ならガード式を強要しない
Style/GuardClause:
  MinBodyLength: 5

# 後置if/unlessを強要しない
Style/IfUnlessModifier:
  Enabled: false

# 正規表現の名前付きキャプチャを許可する
Style/PerlBackrefs:
  Enabled: false

# シンボルの配列に%記法を強要しない
Style/SymbolArray:
  EnforcedStyle: brackets

# マイグレーションファイルについては(&:メソッド名)イディオムを強要しない
Style/SymbolProc:
  Exclude:
    - "db/migrate/*"

########## Metrics ##########

# メソッドの複雑さ：30まで許可する
Metrics/AbcSize:
  Max: 30

# メソッドの複雑さ：10まで許可する
Metrics/CyclomaticComplexity:
  Max: 10

# メソッドの行数：20行まで許可する
Metrics/MethodLength:
  Max: 20

# 分岐の数：10まで許可する
Metrics/PerceivedComplexity:
  Max: 10

# 1行の長さは160文字まで許可する
Metrics/LineLength:
  Max: 160
