require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  # 検査対象から除外する
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "tmp/seeds.rb"
    - "lib/tasks/auto_annotate_models.rake"
  # 警告にCop名を表示する
  DisplayCopNames: true

# 日本語のコメントを許可する
AsciiComments:
  Enabled: false

########## Style ##########

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 文字列リテラルを凍結するためのマジックコメントを強要しない
Style/FrozenStringLiteralComment:
  Enabled: false

# 3行程度ならガード式を強要しない
Style/GuardClause:
  MinBodyLength: 5

# 後置if/unlessを強要しない
Style/IfUnlessModifier:
  Enabled: false

# 正規表現の名前付きキャプチャを許可する
Style/PerlBackrefs:
  Enabled: false

# シンボル配列に%iなどの%記法を強要しない
Style/SymbolArray:
  Enabled: false

# 文字列配列に%wなどの%記法を強要しない
Style/WordArray:
  Enabled: false

# (&:メソッド名)記法が可能なら強要する
Style/SymbolProc:
  # マイグレーションファイルは強要しない
  Exclude:
    - "db/migrate/*"

# ブロック構文を1行なら{...}、複数行ならdo...endに強要する
Style/BlockDelimiters:
  # テストコードは複数行ブロックの{...}も許可する
  Exclude:
    - "spec/**/*"

# 文字列リテラルにはダブルクォートを使用する
Style/StringLiterals:
  EnforcedStyle: double_quotes

########## Metrics ##########

# メソッドの複雑さ：30以上は警告する
Metrics/AbcSize:
  Max: 30

# メソッドの複雑さ：10以上は警告する
Metrics/CyclomaticComplexity:
  Max: 10

# メソッドの行数：20行以上は警告する
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"
    - "app/models/*.rb"

# クラスの行数：350行以上は警告する
Metrics/ClassLength:
  Max: 350

# 分岐の数：10回以上は警告する
Metrics/PerceivedComplexity:
  Max: 10

# ブロックの行数：25行以上は警告する
Metrics/BlockLength:
  # 設定ファイルは除外する
  Exclude:
    - "config/**/*"

########## Lint ##########

# ブロック内で()無しの引数を渡すことを警告する
Lint/AmbiguousBlockAssociation:
  # テストコードは許可する
  Exclude:
    - "spec/**/*"

########## Layout ##########

# Windows以外で開発することになった場合、改行コードをLFに強要する
Layout/EndOfLine:
  EnforcedStyle: lf
  # Enabled: false

# 1行の文字数：160文字以上は警告する(なるべく80文字以下にする)
Layout/LineLength:
  Max: 160

# 複数行に跨る配列の最初の要素は1段インデントする
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# 複数行に跨る引数の最初の引数は1段インデントする
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

########## Naming ##########

# ヒアドキュメントの区切り文字にEOSなど単純な文字列を禁止する
Naming/HeredocDelimiterNaming:
  # テストコードは許可する
  Exclude:
    - "spec/**/*"

# 引数名の末尾の数字はスネークケースにする
Naming/VariableNumber:
  EnforcedStyle: snake_case

########## Rails ##########

# Rails.rootの使用方法を強制しない
Rails/FilePath:
  Enabled: false

# putsなどの利用を警告する
Rails/Output:
  Exclude:
    - "db/seeds.rb"

# html_safeなどの利用を警告する
Rails/OutputSafety:
  Exclude:
    - "app/helpers/markdown_helper.rb"
    - "app/helpers/searches_helper.rb"

########## RSpec ##########

# モックのallow_any_instance_ofを許可する
RSpec/AnyInstance:
  Exclude:
    - "spec/**/*"

# フィーチャースペックのエイリアスメソッドを許可する
RSpec/Capybara/FeatureMethods:
  Exclude:
    - "spec/features/**/*"

# 日本語のcontextを許可する
RSpec/ContextWording:
  Enabled: false

# テスト対象のクラスでもプレフィックスで明示する
RSpec/DescribedClass:
  EnforcedStyle: explicit

# テスト項目の行数：10行まで許可する
RSpec/ExampleLength:
  Max: 10
  # 複数行の配列、ハッシュ、ヒアドキュメントは1行としてカウントする
  CountAsOne: ["array", "hash", "heredoc"]
  # フィーチャースペックは厳しいので除外する
  Exclude:
    - "spec/features/**/*"

# Changeマッチャのスタイル統一を強制しない
RSpec/ExpectChange:
  Enabled: false

# テスト項目のexpectメソッド呼び出し回数：5回以上は警告する
RSpec/MultipleExpectations:
  Max: 5
  # フィーチャースペックは厳しいので除外する
  Exclude:
    - "spec/features/**/*"

# テスト項目のネスト数：5回以上は警告する
RSpec/NestedGroups:
  Max: 5
