version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - public-share:/srv/beginners_db_app/public
      - tmp-share:/srv/beginners_db_app/tmp
    ports:
      - 80:80
      - 443:443
    networks:
      - beginners-db-app-network
    depends_on:
      - app

  app:
    build:
      context: .
    command: rails s -e production
    volumes:
      - .:/srv/beginners_db_app
      - public-share:/srv/beginners_db_app/public
      - tmp-share:/srv/beginners_db_app/tmp
      - log-store:/srv/beginners_db_app/log
    networks:
      - beginners-db-app-network

volumes:
  public-share:
  tmp-share:
  log-store:

networks:
  beginners-db-app-network:
    external: true
