version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/production/nginx/Dockerfile
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 36h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./docker/production/nginx/conf.d:/etc/nginx/conf.d
      - html:/var/www/html
      - letsencrypt:/etc/letsencrypt
      - public-share:/srv/beginners_db_app/public
      - tmp-share:/srv/beginners_db_app/tmp
      - log-nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rails

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - html:/var/www/html
      - letsencrypt:/etc/letsencrypt
      - log-letsencrypt:/var/log/letsencrypt

  rails:
    build:
      context: .
    container_name: rails
    command: rails s -e production
    volumes:
      - .:/srv/beginners_db_app
      - bundle:/usr/local/bundle
      - public-share:/srv/beginners_db_app/public
      - tmp-share:/srv/beginners_db_app/tmp
      - log-rails:/srv/beginners_db_app/log

volumes:
  bundle:
  public-share:
  tmp-share:
  html:
  letsencrypt:
  log-nginx:
  log-rails:
  log-letsencrypt:

networks:
  default:
    name: beginners-db-app-network
    external: true
