version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/development/nginx/Dockerfile
    container_name: nginx
    volumes:
      - public-share:/srv/beginners_db_app/public
      - tmp-share:/srv/beginners_db_app/tmp
      - log-nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    network_mode: "host"
    depends_on:
      - rails

  rails:
    build:
      context: .
    container_name: rails
    command: rails s
    volumes:
      - .:/srv/beginners_db_app
      - public-share:/srv/beginners_db_app/public
      - tmp-share:/srv/beginners_db_app/tmp
      - log-rails:/srv/beginners_db_app/log
    network_mode: "host"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/development/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  db-store:
  public-share:
  tmp-share:
  log-nginx:
  log-rails:
