default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) * ENV.fetch("WEB_CONCURRENCY", 2) %>
  timeout: 5000
  encoding: unicode
  username: beginners_db_app
  # password:
  host: localhost

development:
  <<: *default
  database: beginners_db_app_development

test:
  <<: *default
  database: beginners_db_app_test

production:
  url: <%= ENV["DATABASE_URL"] %>
