default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) * ENV.fetch("WEB_CONCURRENCY", 2) %>
  timeout: 5000
  encoding: unicode
  username: beginners_db_app
  password: beginners_db_app
  host: localhost

development:
  <<: *default
  database: beginners_db_app_development

test:
  <<: *default
  database: beginners_db_app_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:aws, :rds_db_name) %>
  username: <%= Rails.application.credentials.dig(:aws, :rds_username) %>
  password: <%= Rails.application.credentials.dig(:aws, :rds_password) %>
  host: <%= Rails.application.credentials.dig(:aws, :rds_hostname) %>
